
--Example #1
EXECUTE FUNCTION INTO VOLATILE ART(multivar_art)
TD_ARIMAVALIDATE(
  ART_SPEC(
    TABLE_NAME(ARMA_ART_MLE_NONS_3_2)
  ),
  FUNC_PARAMS(FIT_METRICS(1),RESIDUALS(1))
);

--Example #2
EXECUTE FUNCTION
INTO VOLATILE ART(ARMA_EST_RESULTS)
TD_ARIMAESTIMATE(
  SERIES_SPEC( TABLE_NAME(blood2ageandweight),  ROW_AXIS(SEQUENCE(SeqNo)), SERIES_ID(PatientID),
               PAYLOAD(FIELDS(BloodFat), CONTENT(REAL))),
  FUNC_PARAMS( NONSEASONAL(MODEL_ORDER(2,3,1)), CONSTANT(1), COEFF_STATS(1), FIT_METRICS(1),
               RESIDUALS(1), ALGORITHM(MLE), FIT_PERCENTAGE(85), MAX_ITERATIONS(100) ));

EXECUTE FUNCTION INTO VOLATILE ART(ARMA_VAL_RESULTS) 
TD_ARIMAVALIDATE( 
   ART_SPEC(TABLE_NAME(ARMA_EST_RESULTS) ),
   FUNC_PARAMS( FIT_METRICS(1), RESIDUALS(1) )
);

