--Setup for TD_ARIMAESTIMATE:
EXECUTE FUNCTION INTO VOLATILE ART(diff1_souv)
TD_DIFF(
  SERIES_SPEC(
    TABLE_NAME(souvenirtimeseries),
    ROW_AXIS(SEQUENCE(row_axis)),
    SERIES_ID(seriesID),
    PAYLOAD(FIELDS(sales),CONTENT(REAL)) 
  ),
  FUNC_PARAMS(
    LAG(1),
    DIFFERENCES(1),
    SEASONAL_MULTIPLIER(0))
);
EXECUTE FUNCTION INTO VOLATILE ART(diff12_souv)
TD_DIFF(
  SERIES_SPEC(
    TABLE_NAME(diff1_souv),
    ROW_AXIS(SEQUENCE(ROW_I)),
    SERIES_ID(seriesID),
    PAYLOAD(FIELDS(OUT_sales),CONTENT(REAL)) 
  ),
  FUNC_PARAMS(LAG(12), DIFFERENCES(1), SEASONAL_MULTIPLIER(0))
);
