
EXECUTE FUNCTION
INTO VOLATILE ART(ARMA_ART_MLE_SEASON_12)
TD_ARIMAESTIMATE(
  SERIES_SPEC(
    TABLE_NAME(diff12_souv),
    ROW_AXIS(SEQUENCE(ROW_I)), 
    SERIES_ID(seriesID AS SID), 
    PAYLOAD(FIELDS(OUT_OUT_sales), CONTENT(REAL)) 
  ),
  FUNC_PARAMS(
    NONSEASONAL(MODEL_ORDER(2,0,1)), 
    CONSTANT(0), 
    ALGORITHM(MLE),
    COEFF_STATS(1),
    FIT_METRICS(1), 
    RESIDUALS(1), 
    FIT_PERCENTAGE(80) 
  )
);



