--Setup for TD_BINARYSERIESOP:
EXECUTE FUNCTION INTO VOLATILE ART(SMOOTH_SERIES)
TD_SMOOTHMA( SERIES_SPEC(TABLE_NAME(StockDataSet), SERIES_ID  (DataSetID), ROW_AXIS(SEQUENCE(SeqNo)),
   PAYLOAD( FIELDS(Magnitude), CONTENT(REAL))) WHERE DataSetID=556,
 FUNC_PARAMS(
   MA("MEAN"),
   WINDOW(5)
 ),
 OUTPUT_FMT(INDEX_STYLE(FLOW_THROUGH) )
);
