
EXECUTE FUNCTION COLUMNS(OUT_Magnitude AS Magnitude) INTO VOLATILE ART(DETREND_STOCK)
TD_BINARYSERIESOP( 
   SERIES_SPEC(
      TABLE_NAME(StockDataSet), 
      SERIES_ID(DataSetID), ROW_AXIS(SEQUENCE(SeqNo)),
      PAYLOAD(FIELDS(Magnitude), CONTENT(REAL))
   ) 
   WHERE DataSetID=556 AND SeqNo BETWEEN 3 and 50,

   SERIES_SPEC(TABLE_NAME(SMOOTH_SERIES), SERIES_ID(DataSetID),  
      ROW_AXIS(SEQUENCE(ROW_I)),
      PAYLOAD(FIELDS(Magnitude), CONTENT(REAL))
   ) 
   WHERE DataSetID=556,
   FUNC_PARAMS(MATHOP("SUB")),
   INPUT_FMT(INPUT_MODE(ONE2ONE)) 
);


EXECUTE FUNCTION INTO VOLATILE ART (TRENDREMOVED)
TD_BINARYSERIESOP(
    SERIES_SPEC (
      TABLE_NAME (BUOY_TABLE),
      ROW_AXIS (TIMECODE (TD_TIMECODE)),      
      SERIES_ID (BUOYID),
      PAYLOAD (FIELDS (SALINITY), CONTENT (REAL))
    ) WHERE BUOYID=33,
    SERIES_SPEC (
      TABLE_NAME (SMOOTHED_DATA),
      ROW_AXIS (SEQUENCE (ROW_I)),      
	 SERIES_ID (BUOYID),
      PAYLOAD (FIELDS (MAGNITUDE), CONTENT (REAL))
    ) WHERE BUOYID=33,
    FUNC_PARAMS (MATHOP(SUB)),
    INPUT_FMT (INPUT_MODE (ONE2ONE))
);




EXECUTE FUNCTION INTO VOLATILE ART(MATHEXAMPLE)
TD_BINARYSERIESOP(
   SERIES_SPEC( TABLE_NAME(BINARY_COMPLEX_LEFT), ROW_AXIS(SEQUENCE(SEQ)), SERIES_ID(ID),
      PAYLOAD(FIELDS(REAL_VAL,IMAGINARY_VAL), CONTENT(COMPLEX)) 
      ) WHERE ID=1,
   SERIES_SPEC( TABLE_NAME(BINARY_COMPLEX_RIGHT), ROW_AXIS(SEQUENCE(SEQ)), SERIES_ID(ID),
      PAYLOAD(FIELDS(REAL_VAL,IMAGINARY_VAL), CONTENT(COMPLEX)) 
      ) WHERE ID=1,
FUNC_PARAMS( MATHOP(ADD) ),
INPUT_FMT(INPUT_MODE(MANY2ONE))
);

EXECUTE FUNCTION INTO VOLATILE ART(MATHEXAMPLE)
TD_BINARYSERIESOP(
   SERIES_SPEC(TABLE_NAME(BINARY_REALS_LEFT), ROW_AXIS(SEQUENCE(SEQ)),SERIES_ID(ID),
      PAYLOAD(FIELDS(A), CONTENT(REAL)) ),
   SERIES_SPEC(TABLE_NAME(BINARY_REALS_RIGHT), ROW_AXIS(SEQUENCE(SEQ)),SERIES_ID(ID),
      PAYLOAD(FIELDS(B), CONTENT(REAL)) ),
   FUNC_PARAMS( MATHOP(SUB) ),
   INPUT_FMT(INPUT_MODE(MATCH)));
   
   
