
EXECUTE FUNCTION INTO VOLATILE ART(bpg_result)
TD_BREUSCH_PAGAN_GODFREY(
   SERIES_SPEC(TABLE_NAME(ols_residuals),ROW_AXIS(SEQUENCE(row_I)),
      SERIES_ID(id), PAYLOAD(FIELDS(X1,X2,X3,residual),
      CONTENT(MULTIVAR_REAL))),
   FUNC_PARAMS(VARIABLES_COUNT(4),STUDENTIZE(1),SIGNIFICANCE_LEVEL(.01))
);




