
EXECUTE FUNCTION INTO VOLATILE ART(MATHEXAMPLE)
TD_BINARYMATRIXOP(
   MATRIX_SPEC( TABLE_NAME(BINARYM_COMPLEX_LEFT), ROW_AXIS(SEQUENCE(SEQ)), 
      COLUMN_AXIS(SEQUENCE(TICK)), MATRIX_ID(ID),
      PAYLOAD(FIELDS(REAL_VAL,IMAGINARY_VAL), CONTENT(COMPLEX)) ) ,
   MATRIX_SPEC( TABLE_NAME(BINARYM_COMPLEX_RIGHT), ROW_AXIS(SEQUENCE(SEQ)),
      COLUMN_AXIS(SEQUENCE(TICK)), MATRIX_ID(ID),
      PAYLOAD(FIELDS(REAL_VAL,IMAGINARY_VAL), CONTENT(COMPLEX)) ) 
   WHERE ID=1,
   FUNC_PARAMS( MATHOP(ADD) ),
   INPUT_FMT(INPUT_MODE(MANY2ONE))
);


EXECUTE FUNCTION INTO VOLATILE ART(MATHEXAMPLE)
TD_BINARYMATRIXOP(
   MATRIX_SPEC(TABLE_NAME(BINARYM_REALS_LEFT), ROW_AXIS(SEQUENCE(SEQ)),
      COLUMN_AXIS(SEQUENCE(TICK)),MATRIX_ID(ID),
      PAYLOAD(FIELDS(A), CONTENT(REAL)) ) WHERE ID=1,
   MATRIX_SPEC(TABLE_NAME(BINARYM_REALS_RIGHT), ROW_AXIS(SEQUENCE(SEQ)), 
      COLUMN_AXIS(SEQUENCE(TICK)),MATRIX_ID(ID),
      PAYLOAD(FIELDS(A,B,C,D), CONTENT(MULTIVAR_REAL)) ) WHERE ID=1,
   FUNC_PARAMS( MATHOP(ADD) ),
   INPUT_FMT(INPUT_MODE(ONE2ONE))
);

EXECUTE FUNCTION INTO VOLATILE ART(TRENDREMOVED)
TD_BINARYMATRIXOP (
    MATRIX_SPEC (
      TABLE_NAME (BUOY_TABLE),
      ROW_AXIS (TIMECODE (TD_TIMECODE)),
      COLUMN_AXIS(SEQUENCE (TD_SEQNO)), 
      MATRIX_ID (BUOYID),
      PAYLOAD (FIELDS (SALINITY), CONTENT (REAL))      
    ) WHERE BUOYID = 33,
    MATRIX_SPEC (
      TABLE_NAME (SMOOTHED_DATA),
      ROW_AXIS (SEQUENCE (ROW_I)),
      COLUMN_AXIS (SEQUENCE (COLUMN_I)),
      MATRIX_ID (BUOYID),
      PAYLOAD (FIELDS (MAGNITUDE), CONTENT (REAL))
      )
    WHERE BUOYID = 33,
    FUNC_PARAMS (MATHOP (SUB)),
    INPUT_FMT(INPUT_MODE (ONE2ONE))
  );


EXECUTE FUNCTION INTO VOLATILE ART(MATHEXAMPLE)
TD_BINARYMATRIXOP(
   MATRIX_SPEC( TABLE_NAME(BINARYM_COMPLEX_LEFT), ROW_AXIS(SEQUENCE(SEQ)), COLUMN_AXIS(SEQUENCE
      (TICK)), MATRIX_ID(ID), PAYLOAD(FIELDS(REAL_VAL,IMAGINARY_VAL), CONTENT(COMPLEX)) ) ,
   MATRIX_SPEC( TABLE_NAME(BINARYM_COMPLEX_RIGHT), ROW_AXIS(SEQUENCE(SEQ)), COLUMN_AXIS(SEQUENCE
      (TICK)), MATRIX_ID(ID),PAYLOAD(FIELDS(REAL_VAL,IMAGINARY_VAL), CONTENT(COMPLEX)) ) 
   WHERE ID=1,
   FUNC_PARAMS( MATHOP(ADD) ),
   INPUT_FMT(INPUT_MODE(MANY2ONE))
);


EXECUTE FUNCTION INTO VOLATILE ART(MATHEXAMPLE)
TD_BINARYMATRIXOP(
   MATRIX_SPEC(TABLE_NAME(BINARYM_REALS_LEFT), ROW_AXIS(SEQUENCE(SEQ)), COLUMN_AXIS(SEQUENCE
      (TICK)),MATRIX_ID(ID),PAYLOAD(FIELDS(A), CONTENT(REAL)) ),
   MATRIX_SPEC(TABLE_NAME(BINARYM_REALS_RIGHT), ROW_AXIS(SEQUENCE(SEQ)), COLUMN_AXIS(SEQUENCE
      (TICK)),MATRIX_ID(ID),PAYLOAD(FIELDS(B), CONTENT(REAL)) ),
   FUNC_PARAMS( MATHOP(MUL) ),
   INPUT_FMT(INPUT_MODE(MATCH))
);




