--Setup for TD_BREUSCH_GODFREY:
EXECUTE FUNCTION INTO VOLATILE ART(LR_RESULTS)
TD_LINEAR_REGR(
       SERIES_SPEC(TABLE_NAME(HOUSE_VALUES), SERIES_ID(CITYID), ROW_AXIS(TIMECODE(TD_TIMECODE)),
                   PAYLOAD(FIELDS(HOUSE_VAL, SALARY),CONTENT(MULTIVAR_REAL))) WHERE CITYID=33,
       FUNC_PARAMS( FORMULA('Y = B0 + B1*X1'), WEIGHTS(0), ALGORITHM('QR'), COEFF_STATS(1),
                    VARIABLES_COUNT(2), MODEL_STATS(1), RESIDUALS(1)) );
