
EXECUTE FUNCTION INTO VOLATILE ART(ART_Res)
TD_CONVOLVE2(
    MATRIX_SPEC(
      TABLE_NAME(Convolve2ValidLeft),
      MATRIX_ID(ID),
      ROW_AXIS(SEQUENCE(ROW_I)),
      COLUMN_AXIS(SEQUENCE(COLUMN_I)),
      PAYLOAD(FIELDS(B), CONTENT(REAL))
    ),
    MATRIX_SPEC(
      TABLE_NAME(Convolve2ValidRight), MATRIX_ID(ID),
      ROW_AXIS(SEQUENCE(ROW_I)),
      COLUMN_AXIS(SEQUENCE(COLUMN_I)),
      PAYLOAD( FIELDS(A), CONTENT(REAL))
    ),
    INPUT_FMT(INPUT_MODE(MATCH))
);

EXECUTE FUNCTION INTO VOLATILE ART(ConvRes1)
TD_CONVOLVE2(
   MATRIX_SPEC(TABLE_NAME(CONVOLVE2_REALS_LEFT), MATRIX_ID(ID),
      ROW_AXIS(SEQUENCE(ROW_SEQ)),COLUMN_AXIS(SEQUENCE(COL_SEQ)),
      PAYLOAD( FIELDS(A), CONTENT(REAL))),
   MATRIX_SPEC(TABLE_NAME(CONVOLVE2_REALS_RIGHT), MATRIX_ID(ID),
      ROW_AXIS(SEQUENCE(ROW_SEQ)), COLUMN_AXIS(SEQUENCE(COL_SEQ)),
      PAYLOAD( FIELDS(A), CONTENT(REAL))),
   INPUT_FMT(INPUT_MODE(MATCH))
);


