
EXECUTE FUNCTION INTO VOLATILE ART(ConvCmplxResB)
TD_CONVOLVE(
SERIES_SPEC(TABLE_NAME(XCONVOLVE_COMPLEX_LEFTMULTI), SERIES_ID(ID), ROW_AXIS(SEQUENCE(SEQ)),
            PAYLOAD( FIELDS(A_REAL,A_IMAG,B_REAL,B_IMAG,C_REAL,C_IMAG), CONTENT(MULTIVAR_COMPLEX))),
SERIES_SPEC(TABLE_NAME(HCONVOLVE_COMPLEX_RIGHTMULTI), SERIES_ID(ID), ROW_AXIS(SEQUENCE(SEQ)),
            PAYLOAD( FIELDS(A_REAL,A_IMAG,B_REAL,B_IMAG,C_REAL,C_IMAG), CONTENT(MULTIVAR_COMPLEX))),
FUNC_PARAMS(ALGORITHM("CONV_DFFT")),
INPUT_FMT(INPUT_MODE(MATCH)));
   

EXECUTE FUNCTION INTO VOLATILE ART(ConvCmplxResB)
TD_CONVOLVE(
   SERIES_SPEC(TABLE_NAME(XCONVOLVE_COMPLEX_LEFT),SERIES_ID(ID),ROW_AXIS(SEQUENCE(SEQ)),
      PAYLOAD( FIELDS(A_REAL,A_IMAG), CONTENT(MULTIVAR_REAL))),
   SERIES_SPEC(TABLE_NAME(HCONVOLVE_COMPLEX_RIGHT),SERIES_ID(ID),ROW_AXIS(SEQUENCE(SEQ)),
      PAYLOAD( FIELDS(A_REAL,A_IMAG), CONTENT(MULTIVAR_REAL))),
   FUNC_PARAMS(ALGORITHM("CONV_SUMMATION")),
   INPUT_FMT(INPUT_MODE(MATCH)));
