--Example #1
EXECUTE FUNCTION INTO VOLATILE ART(LR_DW)
TD_DURBIN_WATSON(
   SERIES_SPEC( TABLE_NAME(LR_RESIDUALS), SERIES_ID(CITYID),   
      ROW_AXIS(SEQUENCE(ROW_I)), PAYLOAD( FIELDS(RESIDUAL), CONTENT(REAL) )),
   FUNC_PARAMS(EXPLANATORY_COUNT(1),INCLUDE_CONSTANT(1),METHOD(DW_FORMULA),
      SIGNIFICANCE_LEVEL(.05) )
);



--Example #2
EXECUTE FUNCTION
INTO VOLATILE ART(SAV_AR_1)
TD_ARIMAESTIMATE(
        SERIES_SPEC(TABLE_NAME(TimeSeriesDataSetsD4), SERIES_ID(DatasetID), ROW_AXIS(SEQUENCE(SeqNo)),
                    PAYLOAD(FIELDS(Magnitude), CONTENT(REAL))) WHERE DatasetID=552,
        FUNC_PARAMS( NONSEASONAL(MODEL_ORDER(1,0,0)), CONSTANT(1), ALGORITHM(MLE),
                     FIT_PERCENTAGE(70), FIT_METRICS(1), COEFF_STATS(1), RESIDUALS(1), MAX_ITERATIONS(100) ) );
                    
CREATE TABLE AR1_RESIDUALS AS (
EXECUTE FUNCTION
TD_EXTRACT_RESULTS( ART_SPEC(TABLE_NAME(SAV_AR_1), LAYER(ARTFITRESIDUALS) ) ) )  WITH DATA;


EXECUTE FUNCTION INTO VOLATILE ART(SAV_AR1_DW)
TD_DURBIN_WATSON(
   SERIES_SPEC( TABLE_NAME(AR1_RESIDUALS), SERIES_ID(DatasetID),  
      ROW_AXIS(SEQUENCE(ROW_I)), PAYLOAD( FIELDS(RESIDUAL), CONTENT(REAL) )),
   FUNC_PARAMS(EXPLANATORY_COUNT(1),INCLUDE_CONSTANT(1),METHOD(DW_FORMULA),
      SIGNIFICANCE_LEVEL(.05) )
);



