
EXECUTE FUNCTION INTO VOLATILE ART(DFFT2Res)
TD_DFFT2(
   MATRIX_SPEC(TABLE_NAME(DFFT2_TestMatrix16),
   MATRIX_ID(BuoyID),
   ROW_AXIS(SEQUENCE(ROW_I)), 
   COLUMN_AXIS(SEQUENCE(COLUMN_I)),
   PAYLOAD( FIELDS(MAGNITUDE), CONTENT(REAL))),
   FUNC_PARAMS(FREQ_STYLE("K_INTEGRAL"), HUMAN_READABLE(0)),
   OUTPUT_FMT(CONTENT(COMPLEX))
);



