--Setup for TD_DFFTCONV:
EXECUTE FUNCTION INTO VOLATILE ART(DFFT_RAW_OUT)
TD_DFFT(
  SERIES_SPEC(TABLE_NAME(DFFTConv_Real_8_8), SERIES_ID(ID), ROW_AXIS(SEQUENCE(ROW_I)),
              PAYLOAD( FIELDS(MAGNITUDE), CONTENT(REAL))
  ),
  FUNC_PARAMS(
    FREQ_STYLE("K_INTEGRAL"),
    HUMAN_READABLE(0)),
    OUTPUT_FMT(CONTENT(COMPLEX))
);
