
EXECUTE FUNCTION INTO VOLATILE ART(ART2)
TD_DICKEY_FULLER(
   SERIES_SPEC(TABLE_NAME(TimeSeriesDataSetsD4),ROW_AXIS(SEQUENCE(SeqNo)),
      SERIES_ID(DatasetID), PAYLOAD(FIELDS(MAGNITUDE),CONTENT(REAL))),
   FUNC_PARAMS(ALGORITHM('NONE'))
);



