
EXECUTE FUNCTION INTO VOLATILE ART(DFFTCONV_HR_OUT)
TD_DFFTCONV(
   ART_SPEC( TABLE_NAME(DFFT_RAW_OUT)),
   FUNC_PARAMS(CONV(RAW_TO_HR), FREQ_STYLE(K_INTEGRAL) ),
   OUTPUT_FMT(CONTENT(AMPL_PHASE_RAdians))
);


