
EXECUTE FUNCTION
TD_DTW
(
   SERIES_SPEC(TABLE_NAME(dtw_t1),ROW_AXIS(TIMECODE(seq)), SERIES_ID(id),
      PAYLOAD(FIELDS(v), CONTENT(REAL))),
   SERIES_SPEC(TABLE_NAME(dtw_t2),ROW_AXIS(TIMECODE(seq)), SERIES_ID(id),
      PAYLOAD(FIELDS(v),CONTENT(REAL))) WHERE (id) = 1,
   INPUT_FMT(INPUT_MODE(MANY2ONE))
);

EXECUTE FUNCTION 
TD_DTW(
   SERIES_SPEC(TABLE_NAME(dtw_t1), ROW_AXIS(TIMECODE(seq)),SERIES_ID(id),
      PAYLOAD(FIELDS(v),CONTENT(REAL))),
   SERIES_SPEC(TABLE_NAME(dtw_t2), ROW_AXIS(TIMECODE(seq)),SERIES_ID(id),
      PAYLOAD(FIELDS(v), CONTENT(REAL))) WHERE (id) = 1,
   INPUT_FMT(INPUT_MODE(MANY2ONE)),
   FUNC_PARAMS(WARPPATH(1) )
);

EXECUTE FUNCTION 
TD_DTW(
   SERIES_SPEC(TABLE_NAME(dtw_t1), ROW_AXIS(TIMECODE(seq)), SERIES_ID(id),
      PAYLOAD(FIELDS(v),CONTENT(REAL))),
   SERIES_SPEC(TABLE_NAME(dtw_t2), ROW_AXIS(TIMECODE(seq)), SERIES_ID(id),
      PAYLOAD(FIELDS(v),CONTENT(REAL)))WHERE (id) = 1,
   INPUT_FMT(INPUT_MODE(MANY2ONE)),
   FUNC_PARAMS( WARPPATH(2) )
);

EXECUTE FUNCTION
TD_DTW(
   SERIES_SPEC(TABLE_NAME(dtw_t1), ROW_AXIS(TIMECODE(seq)), SERIES_ID(id),
      PAYLOAD(FIELDS(v),CONTENT(REAL))),
   SERIES_SPEC(TABLE_NAME(dtw_t2), ROW_AXIS(TIMECODE(seq)), SERIES_ID(id),
      PAYLOAD(FIELDS(v),CONTENT(REAL)))WHERE (id) = 1,
   INPUT_FMT(INPUT_MODE(MANY2ONE)),
   FUNC_PARAMS( WARPPATH(3) )
);


EXECUTE FUNCTION
TD_DTW(
   SERIES_SPEC(TABLE_NAME(dtw_t1), ROW_AXIS(TIMECODE(seq)), SERIES_ID(id),
      PAYLOAD(FIELDS(v), CONTENT(REAL))),
   SERIES_SPEC(TABLE_NAME(dtw_t2), ROW_AXIS(TIMECODE(seq)), SERIES_ID(id),
      PAYLOAD(FIELDS(v), CONTENT(REAL))) WHERE (id) = 1,
   INPUT_FMT(INPUT_MODE(MANY2ONE)),
   FUNC_PARAMS( DISTANCE('binary') )
);


EXECUTE FUNCTION
TD_DTW(
   SERIES_SPEC(TABLE_NAME(dtw_t1),ROW_AXIS(TIMECODE(seq)), SERIES_ID(id),
      PAYLOAD(FIELDS(v), CONTENT(REAL))),
   SERIES_SPEC(TABLE_NAME(dtw_t2),ROW_AXIS(TIMECODE(seq)), SERIES_ID(id),
      PAYLOAD(FIELDS(v), CONTENT(REAL))) WHERE (id) = 1,
   INPUT_FMT(INPUT_MODE(MANY2ONE)),
   FUNC_PARAMS(RADIUS('1'))
);


