--Setup for TD_FITMETRICS:
EXECUTE FUNCTION INTO VOLATILE ART(ARMA_ART_MLE_NONS_3_2)
TD_ARIMAESTIMATE(
   SERIES_SPEC(TABLE_NAME(fm_blood2ageandweight), ROW_AXIS(SEQUENCE(I)), SERIES_ID(ID),
               PAYLOAD(FIELDS(BloodFat), CONTENT(REAL))),
    FUNC_PARAMS(NONSEASONAL(MODEL_ORDER(3,2,2)), ALGORITHM(MLE), MAX_ITERATIONS(100),
                FIT_PERCENTAGE(60), CONSTANT(1), COEFF_STATS(1), FIT_METRICS(1), RESIDUALS(1)));
EXECUTE FUNCTION INTO VOLATILE ART(ARMAVAL_ART)
TD_ARIMAVALIDATE(
    ART_SPEC(TABLE_NAME(ARMA_ART_MLE_NONS_3_2)),
    FUNC_PARAMS(FIT_METRICS(1), RESIDUALS(1)));
EXECUTE FUNCTION INTO VOLATILE ART(ARMAVAL_ART_RES)
TD_EXTRACT_RESULTS(
    ART_SPEC(TABLE_NAME(ARMAVAL_ART), LAYER(ARTFITRESIDUALS)));
CREATE TABLE FM_RES_INPUT(ID,ROW_I,ACTUAL_VALUE,CALC_VALUE,RESIDUAL) AS
(SEL ID, ROW_I, ACTUAL_VALUE, CALC_VALUE, RESIDUAL
 FROM ARMAVAL_ART_RES) WITH DATA;
