
EXECUTE FUNCTION INTO VOLATILE ART(ART_FMFSTAT)
TD_FITMETRICS(
   SERIES_SPEC(TABLE_NAME(FM_RES_INPUT),ROW_AXIS(Sequence(ROW_I)),SERIES_ID(ID),
     PAYLOAD(FIELDS(ACTUAL_VALUE, CALC_VALUE, RESIDUAL),
        CONTENT(MULTIVAR_REAL))),
   FUNC_PARAMS(VAR_COUNT(5), FSTAT(1), SIGNIFICANCE_LEVEL(0.05))
);



EXECUTE FUNCTION INTO VOLATILE ART(FM_ARTSPEC_OUT)
TD_FITMETRICS(
   ART_SPEC(TABLE_NAME(ARMAVAL_ART),LAYER(ARTFITRESIDUALS)),
   FUNC_PARAMS(VAR_COUNT(5), FSTAT(1), SIGNIFICANCE_LEVEL(0.05))
);




