
EXECUTE FUNCTION INTO VOLATILE ART(GQT1D)
TD_GOLDFELD_QUANDT(
   SERIES_SPEC(TABLE_NAME(GQ_T1), ROW_AXIS(SEQUENCE(X1)), SERIES_ID(SeriesID),
      PAYLOAD(FIELDS(Y1, X1), CONTENT(MULTIVAR_REAL) )
   ),
   FUNC_PARAMS(ORIG_REGR_PARAMCNT(2), OMIT(2), SIGNIFICANCE_LEVEL(0.05) ,
      FORMULA('Y = B0  B1*X1'), ALGORITHM('QR')
   ) 
);



