
EXECUTE FUNCTION INTO VOLATILE ART(mytab)
TD_GENSERIES4FORMULA(
    GENSERIES_SPEC(
       INSTANCE_NAMES('{"BuoyID": 3 }'),
       DT(INTEGER),
       GEN_PAYLOAD(0,1,5)
    ),
    FUNC_PARAMS(FORMULA('Y = 3.0  8.0*X1')), 
    OUTPUT_FMT(INDEX_STYLE(NUMERICAL_SEQUENCE))
);


EXECUTE FUNCTION INTO VOLATILE ART(GEN_SERIES)
TD_GENSERIES4FORMULA(
    SERIES_SPEC(
        TABLE_NAME(ProductionData2), 
        ROW_AXIS(TIMECODE(TD_TIMECODE)), 
        SERIES_ID(ProductID),
    PAYLOAD(FIELDS(BEER_SALES), CONTENT(REAL)) 
    ),
    FUNC_PARAMS(FORMULA('Y = 2.0*X1  SIN(X1)')),
    OUTPUT_FMT(INDEX_STYLE(FLOW_THROUGH))
);


EXECUTE FUNCTION INTO VOLATILE ART(SELFGENSERIES)
TD_GENSERIES4FORMULA(
    GENSERIES_SPEC(
        INSTANCE_NAMES('{ "BuoyID": 3 }'), 
        DT(FLOAT), GEN_PAYLOAD(0.0,1.0,5)
    ),
    FUNC_PARAMS(FORMULA('Y = 3.0  8.0*X1')),
    OUTPUT_FMT(INDEX_STYLE(NUMERICAL_SEQUENCE))
);




