
EXECUTE FUNCTION INTO VOLATILE ART (GEN_SERIES)
TD_GENSERIES4SINUSOIDS (
    SERIES_SPEC (
      TABLE_NAME (ProductionData2),
      ROW_AXIS (TIMECODE (TD_TIMECODE)),
      SERIES_ID (ProductID),
      PAYLOAD (FIELDS (BEER_SALES), CONTENT (REAL))
    ),
    FUNC_PARAMS (PERIODICITIES (0.523, 1.4367)),    
    OUTPUT_FMT (INDEX_STYLE (FLOW_THROUGH))
  );
  

 
