
EXECUTE FUNCTION INTO VOLATILE ART(Results_first)
TD_INPUTVALIDATOR(
   SERIES_SPEC ( TABLE_NAME(BuoyData_Mix), ROW_AXIS(TIMECODE(TD_TIMECODE)),
      SERIES_ID(OceanName, BuoyId), PAYLOAD(FIELDS(Salinity),CONTENT(REAL))
   ),
   FUNC_PARAMS(FAILURE_MODE('FUNC_FIRST'))
);

