--Setup for TD_IDFFT:
EXECUTE FUNCTION  INTO VOLATILE ART(DFFT_RESULTS)
TD_DFFT(
  SERIES_SPEC(TABLE_NAME(MVDFFT8), ROW_AXIS(SEQUENCE(N_SeqNo)), SERIES_ID(SID),
              PAYLOAD(FIELDS(MAGNITUDE1), CONTENT(REAL)) ),
  FUNC_PARAMS(HUMAN_READABLE(1)),
  OUTPUT_FMT(CONTENT(COMPLEX)));
