
EXECUTE FUNCTION INTO VOLATILE ART(ORIG_SERIES)
TD_IDFFT(
   ART_SPEC(TABLE_NAME(DFFT_RESULTS),
      PAYLOAD(FIELDS(REAL_MAGNITUDE1,IMAG_MAGNITUDE1), CONTENT(COMPLEX)) 
   ),
   FUNC_PARAMS(HUMAN_READABLE(1)) 
);  



