
EXECUTE FUNCTION INTO VOLATILE ART(IDFFT2)
TD_IDFFT2(MATRIX_SPEC(TABLE_NAME(DFFT2), MATRIX_ID(BuoyID),
      ROW_AXIS(SEQUENCE(ROW_I)),
 
      COLUMN_AXIS(SEQUENCE(COLUMN_I)),
      PAYLOAD( FIELDS(REAL_MAGNITUDE, IMAG_MAGNITUDE), CONTENT(COMPLEX))),
   FUNC_PARAMS(HUMAN_READABLE(0)) 
);


