
EXECUTE FUNCTION INTO VOLATILE ART(LineSpecRes_river)
TD_LINESPEC(
   SERIES_SPEC(TABLE_NAME(TestRiver), SERIES_ID(BuoyID),ROW_AXIS(SEQUENCE(N_SeqNo)),
      PAYLOAD( FIELDS(MAGNITUDE), CONTENT(REAL))),
   FUNC_PARAMS(FREQ_STYLE("K_PERIODICITY"))
);

