
EXECUTE FUNCTION INTO VOLATILE ART(MULTIVAR_RESULTS)
TD_MULTIVAR_REGR(
  SERIES_SPEC(TABLE_NAME(HOUSE_VALUES), ROW_AXIS(TIMECODE(TD_TIMECODE)), SERIES_ID(CITYID),
              PAYLOAD( FIELDS(HOUSE_VAL, SALARY, MORTGAGE),  CONTENT(MULTIVAR_REAL)) ),
  FUNC_PARAMS( VARIABLES_COUNT(3), WEIGHTS(0), FORMULA('Y = B0  B1*X1   B2*X2'),
               ALGORITHM('QR'), COEFF_STATS(1), MODEL_STATS(1),RESIDUALS(1) )  );

