
EXECUTE FUNCTION INTO VOLATILE ART(MatrixProduct)
TD_MATRIXMULTIPLY(
  MATRIX_SPEC(TABLE_NAME(Mtx1), MATRIX_ID(BuoyID),
              ROW_AXIS(SEQUENCE(row_I)),COLUMN_AXIS(SEQUENCE(column_I)),
              PAYLOAD( FIELDS(speed1),CONTENT(REAL))) where buoyid = 35,
  MATRIX_SPEC(TABLE_NAME(Mtx2), MATRIX_ID(BuoyID),
              ROW_AXIS(SEQUENCE(row_I)),COLUMN_AXIS(SEQUENCE(column_I)),
              PAYLOAD(FIELDS(speed2), CONTENT(REAL))) where buoyid = 35,
  INPUT_FMT(INPUT_MODE(ONE2ONE)) 
);


EXECUTE FUNCTION INTO VOLATILE ART(MatrixProduct)
TD_MATRIXMULTIPLY(
   MATRIX_SPEC(TABLE_NAME(Mtx1), MATRIX_ID(BuoyID),
      ROW_AXIS(SEQUENCE(row_I)), COLUMN_AXIS(SEQUENCE(column_I)),
      PAYLOAD( FIELDS(speed1),CONTENT(REAL))) where buoyid = 35,
   MATRIX_SPEC(TABLE_NAME(Mtx2), MATRIX_ID(BuoyID),
      ROW_AXIS(SEQUENCE(row_I)),COLUMN_AXIS(SEQUENCE(column_I)),
      PAYLOAD(FIELDS(speed2), CONTENT(REAL))) where buoyid = 35,
   INPUT_FMT(INPUT_MODE(MANY2ONE))
);


EXECUTE FUNCTION INTO VOLATILE ART(MatrixProduct)
TD_MATRIXMULTIPLY(
   MATRIX_SPEC(TABLE_NAME(Mtx1), MATRIX_ID(BuoyID),
      ROW_AXIS(SEQUENCE(row_I)),COLUMN_AXIS(SEQUENCE(column_I)),
      PAYLOAD( FIELDS(speed1),CONTENT(REAL))),
   MATRIX_SPEC(TABLE_NAME(Mtx2), MATRIX_ID(BuoyID),
      ROW_AXIS(SEQUENCE(row_I)), COLUMN_AXIS(SEQUENCE(column_I)),
      PAYLOAD(FIELDS(speed2), CONTENT(REAL))),
   INPUT_FMT(INPUT_MODE(MATCH))
);


 for source table data, refer to setup.sql

