
EXECUTE FUNCTION INTO VOLATILE ART(MAMEAN_RESULTS)
TD_MAMEAN(
   SERIES_SPEC(TABLE_NAME(Orders1),SERIES_ID(storeID),
      ROW_AXIS(SEQUENCE(SEQ)),
      PAYLOAD( FIELDS(sales), CONTENT(REAL))),
   FUNC_PARAMS(FORECAST_PERIODS(8), ALGORITHM(MA),
      PREDICTION_INTERVALS('BOTH'),
      FIT_METRICS(1), RESIDUALS(1), K_ORDER(3))
);

