
EXECUTE FUNCTION INTO VOLATILE ART(TMINFO_RESULTS)
TD_MINFO(
   MATRIX_SPEC (
      TABLE_NAME(OCEAN_BUOYS2),
      ROW_AXIS(TIMECODE(TD_TIMECODE)),
      COLUMN_AXIS(SEQUENCE(SPACE)),
      MATRIX_ID(Ocean_Name, BuoyID),
      PAYLOAD(FIELDS(JsonCol.Measure.Salinity),CONTENT(REAL))
   )
);

