--Setup for TD_PLOT :
EXECUTE FUNCTION INTO VOLATILE ART(PWRSPEC_RES) 
TD_POWERSPEC( SERIES_SPEC( TABLE_NAME(TimeSeriesDataSetsD4), SERIES_ID(DataSetID), ROW_AXIS(TIMECODE(TimeValue)),
                          PAYLOAD( FIELDS(Magnitude), CONTENT(REAL)))WHERE DataSetID=552,
             FUNC_PARAMS( FREQ_STYLE("K_RADIANS") ));
EXECUTE FUNCTION COLUMNS(OUT_Magnitude AS Magnitude) INTO VOLATILE ART(ACF_RES_552)
TD_ACF ( SERIES_SPEC(TABLE_NAME(TimeSeriesDataSetsD4),SERIES_ID(DataSetID), ROW_AXIS(TIMECODE(TimeValue)),                             
                             PAYLOAD (FIELDS (Magnitude), CONTENT(REAL))) WHERE DataSetID=552,
                 FUNC_PARAMS(MAXLAGS(26), FUNC_TYPE(0), QSTAT(1), DEMEAN(1), ALPHA(0.05) ));
EXECUTE FUNCTION COLUMNS(OUT_Magnitude AS Magnitude) INTO VOLATILE ART(PACF_RES_552)
TD_PACF ( SERIES_SPEC( TABLE_NAME(TimeSeriesDataSetsD4), SERIES_ID(DataSetID), ROW_AXIS(TIMECODE(TimeValue)),
                       PAYLOAD (FIELDS (Magnitude), CONTENT(REAL))) WHERE DataSetID=552 ,
          FUNC_PARAMS( MAXLAGS(26), UNBIASED(0), INPUT_TYPE(DATA_SERIES), ALGORITHM(LEVINSON_DURBIN ), ALPHA(0.05) ));
