
EXECUTE FUNCTION INTO VOLATILE ART(SAV_AR1_PORTMANBP)
TD_PORTMAN(
   SERIES_SPEC( TABLE_NAME(AR1_VALIDATE_RESIDUALS), SERIES_ID(DatasetID), 
      ROW_AXIS(SEQUENCE(ROW_I)),
      PAYLOAD(FIELDS(RESIDUAL), CONTENT(REAL))) WHERE DatasetID=552,
   FUNC_PARAMS( 
      MAXLAG(2), 
      TEST(BP), 
      DEGREES_FREEDOM(1), 
      SIGNIFICANCE_LEVEL(0.05)
   )
);



EXECUTE FUNCTION INTO VOLATILE ART(SAV_AR1_PORTMANLJB)
TD_PORTMAN(
   SERIES_SPEC( TABLE_NAME(AR1_VALIDATE_RESIDUALS), SERIES_ID(DatasetID), ROW_AXIS            (SEQUENCE(ROW_I)), PAYLOAD(FIELDS(RESIDUAL), CONTENT(REAL))) WHERE DatasetID=552,
   FUNC_PARAMS( 
      MAXLAG(2), 
      TEST(LB), 
      DEGREES_FREEDOM(1),
      SIGNIFICANCE_LEVEL(0.05) 
   )
);




