
EXECUTE FUNCTION INTO VOLATILE ART(pacf_water)
TD_PACF (
   SERIES_SPEC(TABLE_NAME(TestPACF12), ROW_AXIS (SEQUENCE(N_SeqNo)), SERIES_ID(BuoyID),
      PAYLOAD (FIELDS (MAGNITUDE1), CONTENT(REAL))) ,
   FUNC_PARAMS(MAXLAGS(10), UNBIASED(0), INPUT_TYPE(DATA_SERIES),
      ALGORITHM(LEVINSON_DURBIN ), ALPHA(0.05)
   )
);




