
EXECUTE FUNCTION INTO VOLATILE ART (MYTAB)
TD_POWERSPEC (
    SERIES_SPEC (
      TABLE_NAME (TestDFFT8),
      SERIES_ID (BuoyID),
      ROW_AXIS (SEQUENCE (N_SeqNo)),
      PAYLOAD (FIELDS (MAGNITUDE), CONTENT (REAL))
    ),
    FUNC_PARAMS (
      FREQ_STYLE ('K_SAMPLE_RATE'),
      ALGORITHM ('AUTOCORR'),
      WINDOW (WINDOW_NAME ('BARTLETT')
    )
  )
);

EXECUTE FUNCTION INTO VOLATILE ART (power_spec_default)
TD_POWERSPEC (
    SERIES_SPEC (
      TABLE_NAME (TestRiver),
      SERIES_ID (BuoyID),
      ROW_AXIS (SEQUENCE (N_SeqNo)),
      PAYLOAD (FIELDS (MAGNITUDE), CONTENT (REAL))
    ),
    FUNC_PARAMS (FREQ_STYLE ('K_INTEGRAL'))
  );
  


