
EXECUTE FUNCTION INTO VOLATILE ART(ResampledSeries)
TD_RESAMPLE(
   SERIES_SPEC(
       TABLE_NAME(ProductionData),
       ROW_AXIS(TIMECODE(TD_TIMECODE)),
       SERIES_ID(ProductID),
       PAYLOAD(FIELDS(BEER_SALES),CONTENT(REAL))
   ),
   FUNC_PARAMS(
        TIMECODE(
          START_VALUE(TIMESTAMP '20170508 00:00:00'),
          DURATION(MINUTES(30))
        ),
       INTERPOLATE(LINEAR)
   ),
   OUTPUT_FMT(CONTENT(REAL))
);


-- OR:

EXECUTE FUNCTION INTO VOLATILE ART(ResampledSeries)
TD_RESAMPLE(
  SERIES_SPEC(
    TABLE_NAME(ProductionData),
    ROW_AXIS(SEQUENCE(TD_SEQNO)),
    SERIES_ID(ProductID),
    PAYLOAD(FIELDS(BEER_SALES),CONTENT(REAL))
  ),
  FUNC_PARAMS(
    SEQUENCE(
      START_VALUE(0),
      DURATION(1)
    ),
    INTERPOLATE(LINEAR)
  ),
  OUTPUT_FMT(CONTENT(REAL)
  )
);


