
EXECUTE FUNCTION INTO VOLATILE ART(SAV_AR2_SIGNIFPERIOD)
TD_SIGNIF_PERIODICITIES(
   SERIES_SPEC(TABLE_NAME(AR2_VALIDATE_RESIDUALS), SERIES_ID(DatasetID), 
      ROW_AXIS(SEQUENCE(ROW_I)), PAYLOAD(FIELDS(RESIDUAL),CONTENT(REAL))
   ),
   FUNC_PARAMS(PERIODICITIES(2.666666666, 5.333333333, 8.0),SIGNIFICANCE_LEVEL(0.05)
   )
);




