
EXECUTE FUNCTION INTO VOLATILE ART(INFLATION_RES)
TD_SIMPLEEXP(
   SERIES_SPEC(TABLE_NAME(INFLATION),
      SERIES_ID (CountryID), 
      ROW_AXIS(TIMECODE(YEAR_RECORDED)),
      PAYLOAD( FIELDS(INFLATION_RATE), CONTENT(REAL))),
   FUNC_PARAMS(FORECAST_PERIODS(4),
      FORECAST_STARTING_VALUE('MEAN'),
      PREDICTION_INTERVALS('80'), ALPHA(0.1),  
      FIT_METRICS(1), RESIDUALS(1) )
);

