
EXECUTE FUNCTION INTO VOLATILE ART(SELCRT_ART_ARMAEST_CONST1)
TD_SELECTION_CRITERIA(
   ART_SPEC( TABLE_NAME(ARMA_EST_ART_CONST1)),
   FUNC_PARAMS(VAR_COUNT(4),CONSTANT(1),USE_LIKELIHOOD(1))
);



EXECUTE FUNCTION INTO VOLATILE ART(SELCRT_ART_ARMAEST_CONST1)
TD_SELECTION_CRITERIA(
   ART_SPEC(TABLE_NAME(ARMA_EST_ART_CONST1)),
   FUNC_PARAMS(VAR_COUNT(4),CONSTANT(1))
);



