
EXECUTE FUNCTION INTO VOLATILE ART(ArtTable)
TD_SEASONALNORMALIZE(
  SERIES_SPEC(
    TABLE_NAME(StoreSales),
    ROW_AXIS(TIMECODE(TD_TIMECODE)),
    SERIES_ID(StoreID),
    PAYLOAD(
       FIELDS(Sales), CONTENT(REAL)),
    INTERVAL(CAL_MONTHS(1))
    ),
    FUNC_PARAMS(
      SEASON_CYCLE(CYCLES("CAL_YEARS"),
      DURATION(1))
  )
);

EXECUTE FUNCTION INTO VOLATILE ART(NORM_SERIES)
TD_SEASONALNORMALIZE(
  SERIES_SPEC(
    TABLE_NAME(RiverData),
    ROW_AXIS(TIMECODE(timevalue)),
    SERIES_ID(StationID),
    PAYLOAD(
      FIELDS(FlowVelocity), CONTENT(REAL)),
      INTERVAL(CAL_MONTHS(1)) 
  ),
  FUNC_PARAMS(
    SEASON_CYCLE(CYCLES("CAL_MONTHS"),
    DURATION(1))
  ), 
  OUTPUT_FMT(INDEX_STYLE(NUMERICAL_SEQUENCE))
);


EXECUTE FUNCTION INTO VOLATILE ART(NORM_STORE_SALES)
TD_SEASONALNORMALIZE(
   SERIES_SPEC(TABLE_NAME(StoreSales), ROW_AXIS(TIMECODE(TD_TIMECODE)), 
      SERIES_ID(StoreID), PAYLOAD( FIELDS(Sales), CONTENT(REAL)),
      INTERVAL(CAL_MONTHS(1))),
   FUNC_PARAMS(SEASON_CYCLE(CYCLES("CAL_YEARS"), DURATION(1)), SEASON_INFO(3) ),
      OUTPUT_FMT( INDEX_STYLE(FLOW_THROUGH) ) 
);

