--Setup for TD_SELECTION_CRITERIA:
EXECUTE FUNCTION INTO VOLATILE ART(ARMA_EST_ART_CONST1)
TD_ARIMAESTIMATE(
   SERIES_SPEC(TABLE_NAME(blood2ageandweight),ROW_AXIS(SEQUENCE(SeqNo)),SERIES_ID(PatientID),
               PAYLOAD(FIELDS(Age), CONTENT(REAL))),
   FUNC_PARAMS(NONSEASONAL(MODEL_ORDER(1,0,2)),CONSTANT(1),COEFF_STATS(1),
               RESIDUALS(1),FIT_PERCENTAGE(60),ALGORITHM(MLE)));
