--Setup for TD_UNNORMALIZE:
EXECUTE FUNCTION INTO VOLATILE ART(normalizedSales)
  TD_SEASONALNORMALIZE(
      SERIES_SPEC(TABLE_NAME(Sales), ROW_AXIS(TIMECODE(ts)), SERIES_ID(StoreID),
                  PAYLOAD( FIELDS(Sales), CONTENT(REAL)),INTERVAL(CAL_MONTHS(1))),
      FUNC_PARAMS(SEASON_CYCLE(CYCLES("CAL_YEARS"), DURATION(1))),
      OUTPUT_FMT(INDEX_STYLE(FLOW_THROUGH)));
EXECUTE FUNCTION INTO VOLATILE ART(normalizedSales)
  TD_SEASONALNORMALIZE(
      SERIES_SPEC(TABLE_NAME(Sales), ROW_AXIS(TIMECODE(ts)), SERIES_ID(StoreID),
                  PAYLOAD( FIELDS(Sales), CONTENT(REAL)),INTERVAL(CAL_MONTHS(1))),
      FUNC_PARAMS(SEASON_CYCLE(CYCLES("CAL_YEARS"), DURATION(1))),
      OUTPUT_FMT(INDEX_STYLE(FLOW_THROUGH)));
CREATE TABLE metaTable AS
(EXECUTE FUNCTION
TD_EXTRACT_RESULTS(ART_SPEC(TABLE_NAME(normalizedSales), LAYER(ARTMETADATA)))) WITH DATA;
