
EXECUTE FUNCTION
TD_UNDIFF(
    SERIES_SPEC(TABLE_NAME(diff0),SERIES_ID(BuoyId), ROW_AXIS(SEQUENCE(ROW_I)),
        PAYLOAD(FIELDS(Mag), CONTENT(REAL))),
    SERIES_SPEC(TABLE_NAME(BuoyData2),SERIES_ID(BuoyId), ROW_AXIS(SEQUENCE(SeqNo)),
        PAYLOAD(FIELDS(Mag), CONTENT(REAL))
    ),
    FUNC_PARAMS(
      LAG(1),
      DIFFERENCES(1),
      SEASONAL_MULTIPLIER(0)),    
    INPUT_FMT(INPUT_MODE(MATCH))
);


