--Setup for TD_UNDIFF:
EXECUTE FUNCTION COLUMNS(OUT_MAG AS MAG) INTO ART(diff0)
TD_DIFF(
    SERIES_SPEC(TABLE_NAME(BuoyData2),ROW_AXIS(SEQUENCE(SeqNo)),SERIES_ID(BuoyId),
                PAYLOAD(FIELDS(Mag),CONTENT(REAL))),
    FUNC_PARAMS(LAG(1),DIFFERENCES(1),SEASONAL_MULTIPLIER(0)));
