
EXECUTE FUNCTION INTO VOLATILE ART(UNNORM_RES)
TD_UNNORMALIZE(
   SERIES_SPEC(TABLE_NAME(normalizedSales), SERIES_ID( StoreID ), 
      ROW_AXIS( TIMECODE( ROW_I ) ),
      PAYLOAD(FIELDS(Sales), CONTENT(REAL)),INTERVAL(CAL_MONTHS(1))),
      SERIES_SPEC(TABLE_NAME(metaTable), SERIES_ID(StoreID), ROW_AXIS(  
         SEQUENCE(ROW_I)), PAYLOAD(FIELDS(MEAN_Sales,SD_Sales),
         CONTENT(MULTIVAR_REAL))),
   INPUT_FMT(INPUT_MODE(MATCH)),
   OUTPUT_FMT(INDEX_STYLE(FLOW_THROUGH)) 
);

