--Setup for TD_WHITES_GENERAL:
EXECUTE FUNCTION INTO ART(multivar_art)
TD_MULTIVAR_REGR(
    SERIES_SPEC(TABLE_NAME(ageandpressure),ROW_AXIS(SEQUENCE(I)),SERIES_ID(A0),
                PAYLOAD(FIELDS(B, A1, B),CONTENT(MULTIVAR_REAL))),
    FUNC_PARAMS(FORMULA('Y = c + a*X1 + b*X2'),ALGORITHM('QR'),VARIABLES_COUNT(3),
                WEIGHTS(0),COEFF_STATS(1), MODEL_STATS(1), RESIDUALS(1)));
